import { Product } from "./api";

/**
 * Demo products shown when the backend hasn't scraped real data yet.
 * Images are real product-style photos from Unsplash.
 */
export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo-1",
    title: "LED Dog Collar — USB Rechargeable, Waterproof, 3 Modes",
    image_url: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&q=80",
    product_url: "#",
    category: "pets",
    price_usd: 24.99,
    cost_usd: 4.20,
    source: "aliexpress",
    score: {
      overall_score: 87,
      demand_score: 91,
      margin_score: 88,
      competition_score: 78,
      trend_score: 92,
      ai_summary: "High demand pet accessory with strong TikTok trend signal and >80% margin potential.",
    },
    suppliers: [],
    ad_signals: [],
  },
  {
    id: "demo-2",
    title: "Magnetic Phone Stand — 360° Adjustable Desk Mount",
    image_url: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400&h=400&fit=crop&q=80",
    product_url: "#",
    category: "electronics",
    price_usd: 18.99,
    cost_usd: 3.50,
    source: "aliexpress",
    score: {
      overall_score: 81,
      demand_score: 83,
      margin_score: 85,
      competition_score: 71,
      trend_score: 80,
      ai_summary: "Evergreen phone accessory with consistent search volume and lean supply chain.",
    },
    suppliers: [],
    ad_signals: [],
  },
  {
    id: "demo-3",
    title: "Portable Mini Projector — 1080P, 120\" Screen, WiFi & Bluetooth",
    image_url: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=400&h=400&fit=crop&q=80",
    product_url: "#",
    category: "electronics",
    price_usd: 79.99,
    cost_usd: 22.00,
    source: "aliexpress",
    score: {
      overall_score: 76,
      demand_score: 79,
      margin_score: 74,
      competition_score: 68,
      trend_score: 82,
      ai_summary: "Rising search volume for mini projectors on TikTok Shop. High AOV drives strong LTV.",
    },
    suppliers: [],
    ad_signals: [],
  },
  {
    id: "demo-4",
    title: "Posture Corrector Belt — Adjustable Back Support Brace",
    image_url: "https://images.unsplash.com/photo-1571019613576-2b22c76fd955?w=400&h=400&fit=crop&q=80",
    product_url: "#",
    category: "fitness",
    price_usd: 22.99,
    cost_usd: 4.80,
    source: "aliexpress",
    score: {
      overall_score: 73,
      demand_score: 76,
      margin_score: 79,
      competition_score: 65,
      trend_score: 70,
      ai_summary: "Health & wellness niche with low return rates and repeat purchase potential.",
    },
    suppliers: [],
    ad_signals: [],
  },
  {
    id: "demo-5",
    title: "RGB LED Strip Lights — 16ft, App-Controlled, Music Sync",
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&q=80",
    product_url: "#",
    category: "home",
    price_usd: 16.99,
    cost_usd: 3.20,
    source: "tiktok",
    score: {
      overall_score: 84,
      demand_score: 90,
      margin_score: 82,
      competition_score: 72,
      trend_score: 95,
      ai_summary: "Viral on TikTok with 2.4M views in the last 7 days. Strong impulse-buy price point.",
    },
    suppliers: [],
    ad_signals: [],
  },
  {
    id: "demo-6",
    title: "Wireless Earbuds — ANC, 30h Battery, IPX5 Waterproof",
    image_url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&q=80",
    product_url: "#",
    category: "electronics",
    price_usd: 39.99,
    cost_usd: 9.50,
    source: "amazon",
    score: {
      overall_score: 78,
      demand_score: 85,
      margin_score: 77,
      competition_score: 63,
      trend_score: 74,
      ai_summary: "Saturated category but strong margin at this spec level. Differentiate on branding.",
    },
    suppliers: [],
    ad_signals: [],
  },
  {
    id: "demo-7",
    title: "Massage Gun — 20-Speed Deep Tissue Percussion Device",
    image_url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=400&fit=crop&q=80",
    product_url: "#",
    category: "fitness",
    price_usd: 59.99,
    cost_usd: 14.00,
    source: "aliexpress",
    score: {
      overall_score: 80,
      demand_score: 82,
      margin_score: 81,
      competition_score: 70,
      trend_score: 78,
      ai_summary: "Recovery niche with strong post-workout audience on Meta ads. Good upsell potential.",
    },
    suppliers: [],
    ad_signals: [],
  },
  {
    id: "demo-8",
    title: "Silicone Cable Organizer Set — 12-Pack Reusable Ties",
    image_url: "https://images.unsplash.com/photo-1625948515315-3fab93001cc7?w=400&h=400&fit=crop&q=80",
    product_url: "#",
    category: "electronics",
    price_usd: 9.99,
    cost_usd: 1.40,
    source: "aliexpress",
    score: {
      overall_score: 71,
      demand_score: 73,
      margin_score: 87,
      competition_score: 60,
      trend_score: 65,
      ai_summary: "Low AOV but exceptional margin and bundling potential. Great for bundle stores.",
    },
    suppliers: [],
    ad_signals: [],
  },
];

export const isDemoProduct = (id: string) => id.startsWith("demo-");
